# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Launch notebook

on:
  issue_comment:
    types: [created]

jobs:
  serve-notebook:
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v2
    - name: Run jupyter
      run: docker run -p 8889:8888 jupyter/scipy-notebook:17aba6048f44
      
